src/main/perl/CCfg.pm, src/test/perl/test-ccfg.t
it is already tested in initCfg
partially fixes #46
=> CCfg _readConfigFile should not retest if configuration file exists

src/main/perl/CCfg.pm, src/main/perl/Fetch.pm, src/main/perl/JSONProfileTyped.pm, src/test/perl/test-ccfg.t
Add support for a boolean `json_typed` (default false) to the config file to use the `JSONProfileTyped` module to extract typed data from JSON profiles (as opposed to the default `JSONProfileSimple` that treats long and double as strings). This allows for the evaluation of this module and the default might change after a testing period.
=> Support json_typed via config file

src/main/bin/ccm-fetch
Without this, ccm-fetch won't parse the configfile (which leads to serious issues when you set json_typed to true).
=> ccm-fetch: add json_typed as command line option to ccm-fetch

src/main/perl/CacheManager.pm, src/main/perl/Fetch.pm, src/test/perl/test-cachemanager.t
Includes removal of unused cacheFile method which also deals with `last_modified` timestamp
Fixes #39
=> CCM Fetch warn when dealing with "profiles from future" due to timesync issues

src/main/perl/Fetch.pm, src/test/perl/json_typed.t
If not, all scalars have magic tainted flag and are B::PVMG. 
This is mainly an issue for `aii-shellfe` which seems to run with different taint level then e.g. `ccm-fetch`.
=> Fetch using json_typed requires untainted decode_json 

src/main/bin/ccm-fetch, src/main/perl/CCfg.pm, src/main/perl/CacheManager.pm, src/main/perl/Configuration.pm, src/main/perl/Element.pm, src/main/perl/Options.pm, src/test/perl/options.t, src/test/perl/test-cachemanager.t, src/test/perl/test-ccfg.t, src/test/perl/test-configuration.t, src/test/perl/test-element.t, src/test/resources/options.pan
Improve CCM API by clarifying the Configuration initialisation, introduce a smarter `CacheManager->getConfiguration()` or obtain a `Configuration` instance and a `CCM::Options` class derived from `CAF::Options` to create command applications.
=> improve CCM  API with more convience methods and a CCM::Options class

src/main/perl/CCfg.pm, src/main/perl/Fetch.pm, src/test/perl/fetch.t
Hi,
We would like to make use of multiple failover URLs, by making the profile_failover setting comma seperated.
=> support for multiple profile failover urls

pom.xml
Existing configurations may be lost.  According to http://www.mojohaus.org/rpm-maven-plugin/map-params.html this value should mark noreplace explicitly.
=> Mark /etc/ccm.conf as noreplace

src/main/conf/ccm.conf, src/main/perl/CCfg.pm, src/test/perl/test-ccfg.t
($host and $domain can be used for Appconfig's variable expansion, but they are invalid ccm.conf parameters)
Fixes #71
=> Use valid defaults for host and domain in default config file

pom.xml
No reason to define explicitly a version in component pom.xml except very specific needs... Done in main pom.xml.
=> Remove exec-maven-plugin version definition (done in master pom file)

src/main/perl/CacheManager.pm, src/main/perl/Configuration.pm
=> CacheManager: clarify the meaning of the passed cid in an unlocked configuration

src/main/bin/ccm-purge
It is read before the config is initialised, so always gets the default
value of 1 day. Move things round a bit so this is configurable (with
the command line argument taking precedence over the config).
=> Fix purge_time config parameter in ccm-purge.

pom.xml, src/main/perl/JSONProfileSimple.pm, src/main/perl/JSONProfileTyped.pm
Fixes #114 (YUM failure to match Perl-generated requirement on SL5)
This was intended to be a replacement for #115 (not working, see discussion for details) but ended up to be very close... #115 that must be closed when this one is merged. The summary is:
- Perl-generated requirement for version 2.3: doesn't work on SL6 as standard version is 2.27 and because Perl interprets versions as decimal numbers, 2.27 is less than 2.3...
- Perl requirement for v2.3 doesn't generate a RPM version requirement and thus YUM may install the EPEL version 1.47 that will not work, if a version > 2.3 is not present in any repo.
Successfully tested on both SL5 and SL6 (installation + ccm-fetch).
=> perl dependency JSON-XS: set an explicit requirement on RPM version

src/main/conf/quattor-ccm, src/main/perl/CLI.pm, src/main/perl/Element.pm, src/main/perl/Fetch/ProfileCache.pm, src/main/perl/Options.pm, src/main/perl/Path.pm, src/main/perl/Resource.pm, src/main/perl/TextRender.pm, src/main/resources/pancxml_element.tt, src/main/resources/query_resource.tt, src/main/resources/query_scalar.tt, src/main/resources/tests/profiles/basic.pan, src/main/resources/tests/regexps/ncmquery/base, src/main/resources/tests/regexps/ncmquery/whitespace, src/main/resources/tests/regexps/pan/base, src/main/resources/tests/regexps/pan/whitespace, src/main/resources/tests/regexps/pancxml/base, src/main/resources/tests/regexps/pancxml/whitespace, src/main/resources/tests/regexps/query/base, src/main/resources/tests/regexps/query/whitespace, src/main/resources/tests/regexps/tabcompletion/base, src/main/resources/tests/regexps/tabcompletion/whitespace, src/test/perl/01_tt.t, src/test/perl/CCMTest.pm, src/test/perl/escaping.t, src/test/perl/path.t, src/test/perl/tabcompletion.t, src/test/resources/tabcompletion_safe_unescape.pan
Support using `{}` as in pan, and also the controlled unescaping of paths in CLI show and the generation of the tabcompletion file
Backwards incompatible because it changes some output formats
=> Path: support escape path and safe_unescape

src/main/bin/ccm-fetch, src/main/perl/Fetch.pm, src/test/perl/fetch.t
Fixes #75
Backwards incompatible due to change in possible return value of `CCM::Fetch->fetchProfile`.
Requires https://github.com/quattor/aii/pull/207 (otherwise this breaks AII)
=> ccm-fetch report changed profile

src/main/perl/TextRender.pm
Small fix for link issue which makes the documentation fail.
=> Textrender: fix link which fails documentation build

src/main/bin/ccm-fetch
Caused by badly resolved merge conflict in #136 (and overall lack of unittests for `ccm-fetch`)
=> ccm-fetch: add missing CCM::Fetch

src/main/bin/ccm-fetch, src/main/conf/quattor-ccm, src/main/perl/CCfg.pm, src/main/perl/CacheManager.pm, src/main/perl/Configuration.pm, src/main/resources/names/basic/name.tt, src/main/resources/tests/profiles/names.pan, src/main/resources/tests/profiles/names_basic.pan, src/main/resources/tests/regexps/names_basic/basic, src/test/perl/configuration-name.t, src/test/perl/test-cachemanager.t, src/test/perl/test-ccfg.t, src/test/resources/names.pan, src/test/resources/names_no_metadata.pan
Completes work in #122 by adding more configuration/profile information
Related to https://github.com/quattor/template-library-core/pull/127
Fixes #138 as a matter of course.
=> Configuration: add name

src/main/perl/Element.pm, src/main/perl/TextRender.pm, src/test/perl/element-getTree.t, src/test/perl/textrender.t
=> TextRender: cast_double and cast_long fail on non-numeric argument

src/test/perl/configuration-name.t, src/test/resources/names.pan
quattor/template-library-core#147 introduced validation for the branch type which caused this test to fail, using a supported value fixes this.
=> Use a branch type value allowed by the schema when testing

src/main/bin/ccm-purge
This was missed when CCM was restructured in 1713a0348163d79c3ba44ee3f5c7d4129097b68c (merged in 4d4b1c025bdbd632f2a8699ee552eb5d136d262a).
Fixes #175.
=> ccm-purge: Use correct (new) path for DB module

src/main/bin/ccm, src/main/bin/ccm-fetch, src/main/bin/ccm-initialise, src/main/bin/ccm-purge
As described in the link below:
http://search.cpan.org/dist/perl-5.26.0/pod/perldelta.pod#Removal_of_the_current_directory_(%22.%22)_from_@INC
Perls before 5.26 include dot in INC unless taint mode is enabled.
Most script supplied by quattor does have taint enabled except a few.
Here I am using the recommendation to remove dot from `@INC`. This is safe
invocation as if someone enables taint mode or upgrades perl it still does the
right thing.
=> remove '.' from @INC

src/main/perl/CLI.pm, src/main/perl/CacheManager/DB.pm, src/main/perl/CacheManager/Element.pm, src/test/perl/db.t
File descriptors are passed to child processes on POSIX platforms by design,
in the case of CCM, this can lead to these being passed all the way down the call tree
to processes (e.g. daemons) that are started by components.
Setting CLOEXEC disables this behaviour and fixes the potential security risk that this poses.
This problem is tackled in modern OSes in e.g. glibc or even Perl itself when using regular open.
However, this is still an issue for the CCM DB files, since we pass our own flags, bypassing
the default behaviour.
=> CacheManager::DB: set CLOEXEC on tied DB files

src/main/perl/CacheManager/Configuration.pm
Last part of #169, was overlooked in #187.
Blocking for 18.6.
=> CCM::Configuration: remove reference to placeholder

pom.xml
This avoids an error when ncm-cdispd is installed by Anaconda before any
Quattor components would be able to create the directory. It also
creates an official record of who owns the directory, which is also nice.
=> Add /var/lib/ccm to the RPM package

src/main/bin/ccm-purge
Make sure ccm-pruge uses the same URL encoding method as
Fetch::Download, to avoid removing URLs which are in fact still valid.
Fixes issue #124.
=> ccm-purge: Fix cleaning up $CacheDir/data

src/main/perl/Fetch/ProfileCache.pm, src/test/perl/fetch.t
Provide a symlink with the old name for backwards compatibility.
Resolves #204.
=> Fetch: Remove suffix from downloaded profile

pom.xml, src/main/perl/CacheManager/Element.pm, src/main/perl/CacheManager/Encode.pm, src/main/perl/CacheManager/Resource.pm, src/main/perl/Fetch/ProfileCache.pm, src/main/perl/Fetch/XMLPanProfile.pm, src/test/perl/cli.t, src/test/perl/element.t, src/test/perl/encode.t, src/test/perl/property.t, src/test/perl/resource.t, src/test/perl/xmlpan.t
Remove all references to this functionality as it is not supported.
This appears to have been a method for tracking where profile values were changed but was removed after the very first Quattor workshop for performance reasons and was never implemented in the current Java implementation version of panc.
This is backwards incompatible as it changes the on-disk DB format, but the field has always been null.
Add `ccm fetch -f` to the post-install script to ensure the profile is updated immediately.
Resolves #134.
=> Strip out all references to derivation

src/main/perl/Fetch/ProfileCache.pm, src/test/perl/cli.t
=> ProfileCache: Include type in checksum calculation
