quattor/CCM

src/main/perl/Fetch.pm

If an error is returned during DB creation (eg unsupported format), we need
to explicitly cancel the current.cid filehandle, otherwise current.cid
gets updated to point at an empty/broken profile.

Don't update current.cid to a broken database.

---

src/main/perl/DB.pm
src/main/perl/Fetch/ProfileCache.pm
src/main/perl/TextRender.pm

Related to https://github.com/quattor/ncm-lib-blockdevices/issues/59

Localize $@ when using eval

---

src/main/perl/CCfg.pm
src/test/perl/fetch.t
src/test/perl/test-ccfg.t

Enable tabcompletion generation and json_typed by default

---

src/main/perl/Fetch.pm
src/main/perl/Fetch/Download.pm
src/main/perl/Fetch/ProfileCache.pm
src/test/perl/fetch.t

Fixes https://github.com/quattor/maven-tools/issues/92

CCM: fetchProfile should close all CAF::File* instances 

---

src/main/perl/Fetch/ProfileCache.pm

Depends on https://github.com/quattor/CAF/pull/173

ProfileCache: Lock use reporter instance for reporting

---

src/main/bin/ccm

ccm: cli should run in tainted mode

---

src/main/perl/Fetch/Download.pm

Download: don't create empty cache file when none existed before

---

src/main/perl/Element.pm

Element: remove (unused) getUnescapedName method

---

src/main/bin/ccm-fetch
src/main/bin/ccm-initialise
src/main/conf/ccm-fetch.cron
src/main/perl/CCfg.pm

ccm-fetch and ccm-initialise: log to file/syslog

---

src/main/bin/ccm-fetch
src/main/perl/CCfg.pm

ccm-fetch: initCfg is required to get correct permissions

---

src/main/bin/ccm-fetch
src/main/perl/Fetch.pm
src/main/perl/Fetch/Config.pm
src/test/perl/fetch-config.t
src/test/perl/fetch.t

Fetch::Config: export the NOQUATTOR constants

---

src/main/bin/ccm-fetch
src/main/bin/ccm-purge
src/main/conf/ccm.conf
src/main/conf/quattor-ccm
src/main/perl/CCfg.pm
src/main/perl/Fetch.pm
src/main/perl/Fetch/Config.pm
src/main/perl/Fetch/Download.pm
src/main/perl/Fetch/ProfileCache.pm
src/test/perl/test-ccfg.t

Remove unused context and preprocessor options

---

src/main/bin/ccm-fetch
src/main/bin/ccm-initialise

Correct cfgfile option in ccm-fetch and ccm-initialise pod

---

src/main/perl/SyncFile.pm

Syncfile: cleanup unused code and remove any hint that something is (un)locked

---

src/main/perl/Path.pm
src/test/perl/path.t

Path: add /software/components/download/files/ to safe unescape paths

---

src/main/perl/Fetch/Config.pm
src/test/perl/fetch-config.t

Fetch::Config: support valid principal with -

---

src/main/perl/CacheManager.pm
src/main/perl/Fetch.pm
src/main/perl/Fetch/Download.pm

Requires https://github.com/quattor/CAF/pull/203
Based on #152

Fetch::Download: switch to CAF::Download::LWP

---

src/main/perl/CacheManager/Configuration.pm
src/main/perl/Configuration.pm

Configuration: CacheManager::Configuration has to be childclass of placeholder deprecated Configuration

---

src/main/bin/ccm-purge

ccm-purge: fix variable scoping error

---

src/main/perl/CacheManager/Element.pm
src/main/perl/TextRender.pm
src/test/perl/element-getTree.t
src/test/perl/textrender.t
src/test/resources/textrender.pan
src/test/resources/textrender_adv.pan

TextRender: support unescape keys

---

src/main/conf/quattor-ccm
src/main/perl/TextRender.pm
src/test/perl/textrender-format.t
src/test/perl/textrender.t

TextRender: add support for jsonpretty type

---

src/main/perl/CacheManager/DB.pm
src/main/perl/CacheManager/Element.pm
src/main/perl/TextRender.pm

and fix a pod issue in DB, and escape issue in Element.

TextRender: Documentation - make sure code blocks are code blocks

---

src/main/bin/ccm-purge

ccm-purge: close db with close_db

---

src/main/perl/TextRender.pm
src/test/perl/textrender.t

Requires https://github.com/quattor/CAF/pull/274

TextRender: support yaml multi document
